# Kotlin 예외 및 예외 처리

## 1. 예외
예외(Exception)는 프로그램이 정상적으로 실행되지 않을 때 발생하는 문제를 의미합니다. 이는 시스템 오류, 잘못된 사용자 입력, 외부 시스템과의 연결 문제 등 다양한 원인에 의해 발생할 수 있습니다.

Kotlin에서는 모든 예외가 비검사 예외입니다. 이는 예외를 처리하도록 강제하지 않는다는 것을 의미합니다. 반면에 Java에서는 검사 예외(checked exceptions)와 비검사 예외(unchecked exceptions) 두 가지 종류가 있습니다. 검사 예외는 컴파일러가 예외를 처리하도록 강제하는 반면, 비검사 예외는 개발자가 선택적으로 처리할 수 있습니다.

## 2. try-catch
예외가 발생할 수 있는 코드는 `try` 블록 내부에 작성되어야 합니다. `try` 블록은 하나 이상의 `catch` 블록을 가질 수 있으며, 이는 발생할 수 있는 각각의 예외 유형을 처리합니다. Kotlin과 Java 모두 `try-catch` 구문을 사용합니다.

```kotlin
try {
    // 예외가 발생할 수 있는 코드
} catch (e: Exception) {
    // 예외 처리
}
```

## 3. finally
`finally` 블록은 예외가 발생하든 발생하지 않든 항상 실행되는 코드 블록입니다. 이는 주로 리소스를 정리하는데 사용됩니다. Kotlin과 Java 모두 `finally` 블록을 사용합니다.

```kotlin
try {
    // 예외가 발생할 수 있는 코드
} catch (e: Exception) {
    // 예외 처리
} finally {
    // 항상 실행되는 코드
}
```

## 4. throw
`throw` 키워드를 사용하여 특정한 예외를 발생시킬 수 있습니다. Kotlin과 Java 모두 `throw` 키워드를 사용합니다.

```kotlin
throw Exception("이것은 예외입니다.")
```

## 5. try 표현식
Kotlin에서는 `try-catch`를 표현식으로 사용할 수 있습니다. 이는 `try-catch` 구문이 값을 반환할 수 있음을 의미합니다. 이와 같은 특성은 Java에서는 지원하지 않습니다.

```kotlin
val result = try {
    // 예외가 발생할 수 있는 코드
    "Success"
} catch (e: Exception) {
    // 예외 처리
    "Failure"
}
```
이런 식으로 Kotlin에서는 `try-catch`를 표현식으로 사용하여 코드를 더 간결하게 작성할 수 있습니다.
