# Kotlin 고급: 예외처리

**목차**
1. 예외처리란?
2. 예외 처리 방식
    - try-catch
    - use
    - runCatching
    - result
3. 각 방식의 특징과 사용 예시

## 1. 예외처리란?

- 프로그래밍에서 예외처리는 프로그램 실행 중에 발생할 수 있는 오류 상황을 미리 예측하고, 그에 대한 처리를 구현하는 것

## 2. 예외 처리 방식

### 2.1 try-catch

- `try-catch` 블록은 예외가 발생할 가능성이 있는 코드를 `try` 블록 내에 작성하고, 예외가 발생하면 이를 `catch` 블록에서 처리

```kotlin
try {
    val result = 10 / 0
} catch (e: ArithmeticException) {
    println(e)
}
```

### 2.2 use

- `use` 함수는 `Closeable` 인터페이스를 구현한 리소스를 안전하게 사용할 수 있도록 함
- `use` 함수는 블록의 실행이 끝나면 자동으로 리소스를 닫아 줌

```kotlin
FileInputStream("file.txt").use { fis ->
    // do something with fis
}
```

### 2.3 runCatching

`runCatching` 함수는 블록 내부의 코드를 실행하고, 예외가 발생하면 이를 잡아 `Result` 객체를 반환

```kotlin
val result = runCatching {
    10 / 0
}
result.onFailure {
    println(it)
}
```

### 2.4 Result

- `Result` 클래스는 성공적으로 연산된 결과나 발생한 예외를 담을 수 있는 래퍼 클래스
- `onSuccess`나 `onFailure` 함수를 사용하여 결과를 처리 가능

```kotlin
val result: Result<Int> = runCatching {
    10 / 2
}
result.onSuccess {
    println(it)
}.onFailure {
    println(it)
}
```

## 3. 각 방식의 특징과 사용 예시

- 위에서 설명한 각 예외처리 방식은 사용하는 방식에 따라 서로 다른 경우에 적합
- `try-catch` 블록은 전통적인 예외 처리 방식으로, 예외가 발생할 수 있는 코드를 명시적으로 처리할 수 있음 
- `use` 함수는 자동 리소스 관리를 제공하며, `Closeable` 인터페이스를 구현한 리소스를 안전하게 사용하고 해제
- `runCatching` 함수와 `Result` 클래스는 함수형 프로그래밍 스타일로 예외를 처리하며, 성공 또는 실패한 연산의 결과를 보다 명확하게 다룰 수 있다